name: Publish Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authorize
        run: echo "${{ secrets.GH_AUTH_TOKEN }}" | gh auth login --with-token

      - name: Release
        run: cd .scripts && sh ./package.sh
